### ISSUE TITLE
What exactly can we do with this exploit?

### ISSUE THREAD

**Issue by IAmTheNerdNextDoor** [m-gsch/S5Late#1]
I have a 7th gen iPod Nano which I managed to successfully exploit just a few minutes ago, but I'm curious, what can I actually do from here? 

I'm not quite sure what I can make to run here or how I would compile for this. I wonder if I can run a minimal Linux kernel on it.

**Comment by m-gsch** [comment]
You might want to check https://github.com/freemyipod/wInd3x and https://freemyipod.org/wiki/Main_Page.

S5Late is currently being integrated into the wInd3x tooling thanks to q3k. Once that is done you could decrypt/encrypt firmware images, and load your own code.

The bootrom expects executables in the IMG1/S5L file format (see: https://freemyipod.org/wiki/IMG1 and https://theapplewiki.com/wiki/S5L_File_Formats). Currently my code only patches the bootrom to deactivate the signature check so that arbitrary IMG1s can be loaded (formats X509_SIGNED_ENCRYPTED (3) or X509_SIGNED (4) ).

Regarding running Linux, the first step is to get U-Boot running and from there create a proper device tree with drivers. That's still far away and it requires a lot of reverse engineering work but you can see some initial attempts for older iPod Nano versions by q3k (https://github.com/freemyipod/u-boot & https://github.com/freemyipod/linux and a talk https://www.youtube.com/watch?v=WQtt7O5OXe0).

If you are interested in getting involved I would recommend joining the freemyipod Discord (https://freemyipod.org/wiki/Contact) 

Apologies for the late reply :)

**Comment by IAmTheNerdNextDoor** [comment]
> You might want to check https://github.com/freemyipod/wInd3x and https://freemyipod.org/wiki/Main_Page.
> 
> S5Late is currently being integrated into the wInd3x tooling thanks to q3k. Once that is done you could decrypt/encrypt firmware images, and load your own code.
> 
> The bootrom expects executables in the IMG1/S5L file format (see: https://freemyipod.org/wiki/IMG1 and https://theapplewiki.com/wiki/S5L_File_Formats). Currently my code only patches the bootrom to deactivate the signature check so that arbitrary IMG1s can be loaded (formats X509_SIGNED_ENCRYPTED (3) or X509_SIGNED (4) ).
> 
> Regarding running Linux, the first step is to get U-Boot running and from there create a proper device tree with drivers. That's still far away and it requires a lot of reverse engineering work but you can see some initial attempts for older iPod Nano versions by q3k (https://github.com/freemyipod/u-boot & https://github.com/freemyipod/linux and a talk https://www.youtube.com/watch?v=WQtt7O5OXe0).
> 
> If you are interested in getting involved I would recommend joining the freemyipod Discord (https://freemyipod.org/wiki/Contact)
> 
> Apologies for the late reply :)

It's all good!

I may try and join at some point if I properly get interested. For now, I'm just toying around with what I can currently do. I'll also take a look at the other links you sent too.

Thanks!
